[package]
name = "rob"
version = "1.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"


[lib]
crate-type = ["rlib"]
name = "rob"


[[bin]]
name = "rob"
path = "src/main.rs"
